# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comSerialWidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget
import userComboBox


class Ui_Form(QWidget):  # object
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(836, 516)

        # QMainWindow
        self.mainWidget = QWidget(Form)
        self.setCentralWidget(self.mainWidget)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.mainWidget)
        # QDialog
        # self.verticalLayout_19 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.textBrowserReceive = QtWidgets.QTextBrowser()
        self.textBrowserReceive.setAcceptRichText(False)
        self.textBrowserReceive.setOpenLinks(False)
        self.textBrowserReceive.setObjectName("textBrowserReceive")
        self.verticalLayout_18.addWidget(self.textBrowserReceive)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.textEditSend = QtWidgets.QTextEdit()
        self.textEditSend.setAcceptRichText(False)
        self.textEditSend.setObjectName("textEditSend")
        self.verticalLayout_15.addWidget(self.textEditSend)
        self.comboBoxSndHistory = QtWidgets.QComboBox()
        self.comboBoxSndHistory.setObjectName("comboBoxSndHistory")
        self.verticalLayout_15.addWidget(self.comboBoxSndHistory)
        self.horizontalLayout_7.addLayout(self.verticalLayout_15)
        self.line_4 = QtWidgets.QFrame()
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_7.addWidget(self.line_4)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem1)
        self.pushButtonSend = QtWidgets.QPushButton()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSend.setFont(font)
        self.pushButtonSend.setObjectName("pushButtonSend")
        self.verticalLayout_14.addWidget(self.pushButtonSend)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem2)
        self.pushButtonClear = QtWidgets.QPushButton()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonClear.setFont(font)
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.verticalLayout_14.addWidget(self.pushButtonClear)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_14)
        self.verticalLayout_18.addLayout(self.horizontalLayout_7)
        self.verticalLayout_18.setStretch(0, 8)
        self.verticalLayout_18.setStretch(1, 1)
        self.verticalLayout_18.setStretch(2, 3)
        self.horizontalLayout_9.addLayout(self.verticalLayout_18)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.groupBox_5 = QtWidgets.QGroupBox()
        font = QtGui.QFont()
        font.setItalic(False)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        # self.comboBoxPort = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBoxPort = userComboBox.userComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPort.sizePolicy().hasHeightForWidth())
        self.comboBoxPort.setSizePolicy(sizePolicy)
        self.comboBoxPort.setObjectName("comboBoxPort")
        self.horizontalLayout_2.addWidget(self.comboBoxPort)
        self.pushButtonOpen = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOpen.setFont(font)
        self.pushButtonOpen.setCheckable(True)
        self.pushButtonOpen.setChecked(False)
        self.pushButtonOpen.setObjectName("pushButtonOpen")
        self.horizontalLayout_2.addWidget(self.pushButtonOpen)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBoxBand = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBoxBand.setObjectName("comboBoxBand")
        self.comboBoxBand.addItem("")
        self.comboBoxBand.addItem("")
        self.comboBoxBand.addItem("")
        self.comboBoxBand.addItem("")
        self.comboBoxBand.addItem("")
        self.horizontalLayout.addWidget(self.comboBoxBand)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_datasize = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_datasize.setObjectName("groupBox_datasize")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_datasize)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButtonData8Bit = QtWidgets.QRadioButton(self.groupBox_datasize)
        self.radioButtonData8Bit.setChecked(True)
        self.radioButtonData8Bit.setObjectName("radioButtonData8Bit")
        self.verticalLayout.addWidget(self.radioButtonData8Bit)
        self.radioButtonData7Bit = QtWidgets.QRadioButton(self.groupBox_datasize)
        self.radioButtonData7Bit.setObjectName("radioButtonData7Bit")
        self.verticalLayout.addWidget(self.radioButtonData7Bit)
        self.radioButtonData6Bit = QtWidgets.QRadioButton(self.groupBox_datasize)
        self.radioButtonData6Bit.setObjectName("radioButtonData6Bit")
        self.verticalLayout.addWidget(self.radioButtonData6Bit)
        self.radioButtonData5Bit = QtWidgets.QRadioButton(self.groupBox_datasize)
        self.radioButtonData5Bit.setObjectName("radioButtonData5Bit")
        self.verticalLayout.addWidget(self.radioButtonData5Bit)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addWidget(self.groupBox_datasize)
        self.groupBox_parity = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_parity.setObjectName("groupBox_parity")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_parity)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButtonParityNone = QtWidgets.QRadioButton(self.groupBox_parity)
        self.radioButtonParityNone.setChecked(True)
        self.radioButtonParityNone.setObjectName("radioButtonParityNone")
        self.verticalLayout_3.addWidget(self.radioButtonParityNone)
        self.radioButtonParityEven = QtWidgets.QRadioButton(self.groupBox_parity)
        self.radioButtonParityEven.setObjectName("radioButtonParityEven")
        self.verticalLayout_3.addWidget(self.radioButtonParityEven)
        self.radioButtonParityOdd = QtWidgets.QRadioButton(self.groupBox_parity)
        self.radioButtonParityOdd.setObjectName("radioButtonParityOdd")
        self.verticalLayout_3.addWidget(self.radioButtonParityOdd)
        self.radioButtonParityMark = QtWidgets.QRadioButton(self.groupBox_parity)
        self.radioButtonParityMark.setObjectName("radioButtonParityMark")
        self.verticalLayout_3.addWidget(self.radioButtonParityMark)
        self.radioButtonSpace = QtWidgets.QRadioButton(self.groupBox_parity)
        self.radioButtonSpace.setObjectName("radioButtonSpace")
        self.verticalLayout_3.addWidget(self.radioButtonSpace)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.addWidget(self.groupBox_parity)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBoxFlowCtrl = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBoxFlowCtrl.setObjectName("checkBoxFlowCtrl")
        self.verticalLayout_4.addWidget(self.checkBoxFlowCtrl)
        self.verticalLayout_8.addWidget(self.groupBox_4)
        self.groupBox_stops = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_stops.setObjectName("groupBox_stops")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_stops)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButtonStop1Bit = QtWidgets.QRadioButton(self.groupBox_stops)
        self.radioButtonStop1Bit.setChecked(True)
        self.radioButtonStop1Bit.setObjectName("radioButtonStop1Bit")
        self.verticalLayout_2.addWidget(self.radioButtonStop1Bit)
        self.radioButtonStop1_5Bit = QtWidgets.QRadioButton(self.groupBox_stops)
        self.radioButtonStop1_5Bit.setObjectName("radioButtonStop1_5Bit")
        self.verticalLayout_2.addWidget(self.radioButtonStop1_5Bit)
        self.radioButtonStop2Bit = QtWidgets.QRadioButton(self.groupBox_stops)
        self.radioButtonStop2Bit.setObjectName("radioButtonStop2Bit")
        self.verticalLayout_2.addWidget(self.radioButtonStop2Bit)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_8.addWidget(self.groupBox_stops)
        self.verticalLayout_8.setStretch(1, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.verticalLayout_17.addWidget(self.groupBox_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem4)
        self.line_2 = QtWidgets.QFrame()
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_17.addWidget(self.line_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem5)
        self.groupBox_rcv = QtWidgets.QGroupBox()
        font = QtGui.QFont()
        font.setItalic(False)
        self.groupBox_rcv.setFont(font)
        self.groupBox_rcv.setFlat(False)
        self.groupBox_rcv.setObjectName("groupBox_rcv")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_rcv)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioButtonRxAscii = QtWidgets.QRadioButton(self.groupBox_rcv)
        self.radioButtonRxAscii.setChecked(True)
        self.radioButtonRxAscii.setObjectName("radioButtonRxAscii")
        self.horizontalLayout_8.addWidget(self.radioButtonRxAscii)
        self.checkBoxRxRecordTime = QtWidgets.QCheckBox(self.groupBox_rcv)
        self.checkBoxRxRecordTime.setObjectName("checkBoxRxRecordTime")
        self.horizontalLayout_8.addWidget(self.checkBoxRxRecordTime)
        self.checkBoxRxAutoCLRF = QtWidgets.QCheckBox(self.groupBox_rcv)
        self.checkBoxRxAutoCLRF.setObjectName("checkBoxRxAutoCLRF")
        self.horizontalLayout_8.addWidget(self.checkBoxRxAutoCLRF)
        self.verticalLayout_13.addLayout(self.horizontalLayout_8)
        self.radioButtonRxHex = QtWidgets.QRadioButton(self.groupBox_rcv)
        self.radioButtonRxHex.setObjectName("radioButtonRxHex")
        self.verticalLayout_13.addWidget(self.radioButtonRxHex)
        self.verticalLayout_17.addWidget(self.groupBox_rcv)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem6)
        self.line_3 = QtWidgets.QFrame()
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_17.addWidget(self.line_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem7)
        self.groupBox_snd = QtWidgets.QGroupBox()
        self.groupBox_snd.setObjectName("groupBox_snd")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_snd)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButtonTxAscii = QtWidgets.QRadioButton(self.groupBox_snd)
        self.radioButtonTxAscii.setChecked(True)
        self.radioButtonTxAscii.setObjectName("radioButtonTxAscii")
        self.horizontalLayout_6.addWidget(self.radioButtonTxAscii)
        self.checkBoxTxAutoCRLF = QtWidgets.QCheckBox(self.groupBox_snd)
        self.checkBoxTxAutoCRLF.setObjectName("checkBoxTxAutoCRLF")
        self.horizontalLayout_6.addWidget(self.checkBoxTxAutoCRLF)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.radioButtonTxHex = QtWidgets.QRadioButton(self.groupBox_snd)
        self.radioButtonTxHex.setObjectName("radioButtonTxHex")
        self.verticalLayout_12.addWidget(self.radioButtonTxHex)
        self.line = QtWidgets.QFrame(self.groupBox_snd)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_12.addWidget(self.line)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBoxTxPeriodEnable = QtWidgets.QCheckBox(self.groupBox_snd)
        self.checkBoxTxPeriodEnable.setObjectName("checkBoxTxPeriodEnable")
        self.horizontalLayout_5.addWidget(self.checkBoxTxPeriodEnable)
        self.lineEditPeriodMs = QtWidgets.QLineEdit(self.groupBox_snd)
        self.lineEditPeriodMs.setObjectName("lineEditPeriodMs")
        self.horizontalLayout_5.addWidget(self.lineEditPeriodMs)
        self.label_2 = QtWidgets.QLabel(self.groupBox_snd)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        self.verticalLayout_16.addLayout(self.verticalLayout_12)
        self.verticalLayout_17.addWidget(self.groupBox_snd)
        self.horizontalLayout_9.addLayout(self.verticalLayout_17)
        self.horizontalLayout_9.setStretch(0, 1)
        self.verticalLayout_19.addLayout(self.horizontalLayout_9)
        self.label.setBuddy(self.comboBoxBand)
        self.label_2.setBuddy(self.lineEditPeriodMs)

        self.retranslateUi(Form)
        self.comboBoxBand.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButtonSend.setText(_translate("Form", "发送"))
        self.pushButtonClear.setText(_translate("Form", "清空"))
        self.groupBox_5.setTitle(_translate("Form", "串口配置"))
        self.pushButtonOpen.setText(_translate("Form", "打开"))
        self.label.setText(_translate("Form", "波特率"))
        self.comboBoxBand.setCurrentText(_translate("Form", "1200"))
        self.comboBoxBand.setItemText(0, _translate("Form", "300"))
        self.comboBoxBand.setItemText(1, _translate("Form", "600"))
        self.comboBoxBand.setItemText(2, _translate("Form", "1200"))
        self.comboBoxBand.setItemText(3, _translate("Form", "New Item"))
        self.comboBoxBand.setItemText(4, _translate("Form", "New Item"))
        self.groupBox_datasize.setTitle(_translate("Form", "数据位"))
        self.radioButtonData8Bit.setText(_translate("Form", "8Bit"))
        self.radioButtonData7Bit.setText(_translate("Form", "7Bit"))
        self.radioButtonData6Bit.setText(_translate("Form", "6Bit"))
        self.radioButtonData5Bit.setText(_translate("Form", "5Bit"))
        self.groupBox_parity.setTitle(_translate("Form", "校验位"))
        self.radioButtonParityNone.setText(_translate("Form", "None"))
        self.radioButtonParityEven.setText(_translate("Form", "Even"))
        self.radioButtonParityOdd.setText(_translate("Form", "Odd"))
        self.radioButtonParityMark.setText(_translate("Form", "Mark"))
        self.radioButtonSpace.setText(_translate("Form", "Space"))
        self.groupBox_4.setTitle(_translate("Form", "硬件流控"))
        self.checkBoxFlowCtrl.setText(_translate("Form", "RTS/CTS"))
        self.groupBox_stops.setTitle(_translate("Form", "停止位"))
        self.radioButtonStop1Bit.setText(_translate("Form", "1Bit"))
        self.radioButtonStop1_5Bit.setText(_translate("Form", "1.5Bit"))
        self.radioButtonStop2Bit.setText(_translate("Form", "2Bit"))
        self.groupBox_rcv.setTitle(_translate("Form", "接收设置"))
        self.radioButtonRxAscii.setText(_translate("Form", "ASCII"))
        self.checkBoxRxRecordTime.setText(_translate("Form", "记录时间"))
        self.checkBoxRxAutoCLRF.setText(_translate("Form", "自动换行"))
        self.radioButtonRxHex.setText(_translate("Form", "Hex"))
        self.groupBox_snd.setTitle(_translate("Form", "发送设置"))
        self.radioButtonTxAscii.setText(_translate("Form", "ASCII"))
        self.checkBoxTxAutoCRLF.setText(_translate("Form", "后缀CR/LF"))
        self.radioButtonTxHex.setText(_translate("Form", "Hex"))
        self.checkBoxTxPeriodEnable.setText(_translate("Form", "周期发送"))
        self.lineEditPeriodMs.setText(_translate("Form", "1000"))
        self.label_2.setText(_translate("Form", "ms"))
