# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import userComboBox
class Ui_SerialAssistantLXL(object):
    def setupUi(self, SerialAssistantLXL):
        SerialAssistantLXL.setObjectName("SerialAssistantLXL")
        SerialAssistantLXL.resize(867, 635)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/images/Picture/7.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SerialAssistantLXL.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(SerialAssistantLXL)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.dockWidget = QtWidgets.QDockWidget(self.centralwidget)
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frameDisplay = QtWidgets.QFrame(self.dockWidgetContents)
        self.frameDisplay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameDisplay.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameDisplay.setObjectName("frameDisplay")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frameDisplay)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.textBrowserReceive = QtWidgets.QTextBrowser(self.frameDisplay)
        self.textBrowserReceive.setAcceptRichText(False)
        self.textBrowserReceive.setOpenLinks(False)
        self.textBrowserReceive.setObjectName("textBrowserReceive")
        self.verticalLayout_21.addWidget(self.textBrowserReceive)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.textEditSend = QtWidgets.QTextEdit(self.frameDisplay)
        self.textEditSend.setAcceptRichText(False)
        self.textEditSend.setObjectName("textEditSend")
        self.verticalLayout_22.addWidget(self.textEditSend)
        self.comboBoxSndHistory = QtWidgets.QComboBox(self.frameDisplay)
        self.comboBoxSndHistory.setObjectName("comboBoxSndHistory")
        self.verticalLayout_22.addWidget(self.comboBoxSndHistory)
        self.horizontalLayout_13.addLayout(self.verticalLayout_22)
        self.line_5 = QtWidgets.QFrame(self.frameDisplay)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_13.addWidget(self.line_5)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem1)
        self.pushButtonSend = QtWidgets.QPushButton(self.frameDisplay)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSend.setFont(font)
        self.pushButtonSend.setCheckable(True)
        self.pushButtonSend.setObjectName("pushButtonSend")
        self.verticalLayout_23.addWidget(self.pushButtonSend)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem2)
        self.pushButtonClear = QtWidgets.QPushButton(self.frameDisplay)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonClear.setFont(font)
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.verticalLayout_23.addWidget(self.pushButtonClear)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem3)
        self.horizontalLayout_13.addLayout(self.verticalLayout_23)
        self.verticalLayout_21.addLayout(self.horizontalLayout_13)
        self.verticalLayout_21.setStretch(0, 8)
        self.verticalLayout_21.setStretch(1, 1)
        self.verticalLayout_21.setStretch(2, 3)
        self.verticalLayout_20.addLayout(self.verticalLayout_21)
        self.horizontalLayout_12.addWidget(self.frameDisplay)
        self.frameConfigWin = QtWidgets.QFrame(self.dockWidgetContents)
        self.frameConfigWin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameConfigWin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameConfigWin.setObjectName("frameConfigWin")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frameConfigWin)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.verticalLayoutSerial = QtWidgets.QVBoxLayout()
        self.verticalLayoutSerial.setObjectName("verticalLayoutSerial")
        self.groupBoxSerialSet = QtWidgets.QGroupBox(self.frameConfigWin)
        font = QtGui.QFont()
        font.setItalic(False)
        self.groupBoxSerialSet.setFont(font)
        self.groupBoxSerialSet.setObjectName("groupBoxSerialSet")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.groupBoxSerialSet)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        # self.comboBoxPort = QtWidgets.QComboBox(self.groupBoxSerialSet)
        self.comboBoxPort = userComboBox.userComboBox(self.groupBoxSerialSet)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPort.sizePolicy().hasHeightForWidth())
        self.comboBoxPort.setSizePolicy(sizePolicy)
        self.comboBoxPort.setObjectName("comboBoxPort")
        self.comboBoxPort.addItem("")
        self.horizontalLayout_14.addWidget(self.comboBoxPort)
        self.pushButtonOpen = QtWidgets.QPushButton(self.groupBoxSerialSet)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOpen.setFont(font)
        self.pushButtonOpen.setCheckable(True)
        self.pushButtonOpen.setChecked(False)
        self.pushButtonOpen.setObjectName("pushButtonOpen")
        self.horizontalLayout_14.addWidget(self.pushButtonOpen)
        self.horizontalLayout_14.setStretch(0, 1)
        self.verticalLayout_26.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_3 = QtWidgets.QLabel(self.groupBoxSerialSet)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_16.addWidget(self.label_3)
        self.comboBoxBand = QtWidgets.QComboBox(self.groupBoxSerialSet)
        self.comboBoxBand.setCurrentText("")
        self.comboBoxBand.setObjectName("comboBoxBand")
        self.horizontalLayout_16.addWidget(self.comboBoxBand)
        self.horizontalLayout_16.setStretch(1, 1)
        self.verticalLayout_27.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.groupBox_datasize = QtWidgets.QGroupBox(self.groupBoxSerialSet)
        self.groupBox_datasize.setObjectName("groupBox_datasize")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.groupBox_datasize)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.radioButtonData8Bit = QtWidgets.QRadioButton(self.groupBox_datasize)
        self.radioButtonData8Bit.setChecked(True)
        self.radioButtonData8Bit.setObjectName("radioButtonData8Bit")
        self.verticalLayout_29.addWidget(self.radioButtonData8Bit)
        self.radioButtonData7Bit = QtWidgets.QRadioButton(self.groupBox_datasize)
        self.radioButtonData7Bit.setObjectName("radioButtonData7Bit")
        self.verticalLayout_29.addWidget(self.radioButtonData7Bit)
        self.radioButtonData6Bit = QtWidgets.QRadioButton(self.groupBox_datasize)
        self.radioButtonData6Bit.setObjectName("radioButtonData6Bit")
        self.verticalLayout_29.addWidget(self.radioButtonData6Bit)
        self.radioButtonData5Bit = QtWidgets.QRadioButton(self.groupBox_datasize)
        self.radioButtonData5Bit.setObjectName("radioButtonData5Bit")
        self.verticalLayout_29.addWidget(self.radioButtonData5Bit)
        self.verticalLayout_28.addLayout(self.verticalLayout_29)
        self.horizontalLayout_17.addWidget(self.groupBox_datasize)
        self.groupBoxParity = QtWidgets.QGroupBox(self.groupBoxSerialSet)
        self.groupBoxParity.setObjectName("groupBoxParity")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.groupBoxParity)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.radioButtonParityNone = QtWidgets.QRadioButton(self.groupBoxParity)
        self.radioButtonParityNone.setChecked(True)
        self.radioButtonParityNone.setObjectName("radioButtonParityNone")
        self.verticalLayout_31.addWidget(self.radioButtonParityNone)
        self.radioButtonParityEven = QtWidgets.QRadioButton(self.groupBoxParity)
        self.radioButtonParityEven.setObjectName("radioButtonParityEven")
        self.verticalLayout_31.addWidget(self.radioButtonParityEven)
        self.radioButtonParityOdd = QtWidgets.QRadioButton(self.groupBoxParity)
        self.radioButtonParityOdd.setObjectName("radioButtonParityOdd")
        self.verticalLayout_31.addWidget(self.radioButtonParityOdd)
        self.radioButtonParityMark = QtWidgets.QRadioButton(self.groupBoxParity)
        self.radioButtonParityMark.setObjectName("radioButtonParityMark")
        self.verticalLayout_31.addWidget(self.radioButtonParityMark)
        self.radioButtonSpace = QtWidgets.QRadioButton(self.groupBoxParity)
        self.radioButtonSpace.setObjectName("radioButtonSpace")
        self.verticalLayout_31.addWidget(self.radioButtonSpace)
        self.verticalLayout_30.addLayout(self.verticalLayout_31)
        self.horizontalLayout_17.addWidget(self.groupBoxParity)
        self.verticalLayout_27.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_15.addLayout(self.verticalLayout_27)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.groupBoxHardFlowCtl = QtWidgets.QGroupBox(self.groupBoxSerialSet)
        self.groupBoxHardFlowCtl.setObjectName("groupBoxHardFlowCtl")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.groupBoxHardFlowCtl)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.checkBoxFlowCtrl = QtWidgets.QCheckBox(self.groupBoxHardFlowCtl)
        self.checkBoxFlowCtrl.setObjectName("checkBoxFlowCtrl")
        self.verticalLayout_33.addWidget(self.checkBoxFlowCtrl)
        self.verticalLayout_32.addWidget(self.groupBoxHardFlowCtl)
        self.groupBoxStops = QtWidgets.QGroupBox(self.groupBoxSerialSet)
        self.groupBoxStops.setObjectName("groupBoxStops")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.groupBoxStops)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.radioButtonStop1Bit = QtWidgets.QRadioButton(self.groupBoxStops)
        self.radioButtonStop1Bit.setChecked(True)
        self.radioButtonStop1Bit.setObjectName("radioButtonStop1Bit")
        self.verticalLayout_35.addWidget(self.radioButtonStop1Bit)
        self.radioButtonStop1_5Bit = QtWidgets.QRadioButton(self.groupBoxStops)
        self.radioButtonStop1_5Bit.setObjectName("radioButtonStop1_5Bit")
        self.verticalLayout_35.addWidget(self.radioButtonStop1_5Bit)
        self.radioButtonStop2Bit = QtWidgets.QRadioButton(self.groupBoxStops)
        self.radioButtonStop2Bit.setObjectName("radioButtonStop2Bit")
        self.verticalLayout_35.addWidget(self.radioButtonStop2Bit)
        self.verticalLayout_34.addLayout(self.verticalLayout_35)
        self.verticalLayout_32.addWidget(self.groupBoxStops)
        self.verticalLayout_32.setStretch(1, 1)
        self.horizontalLayout_15.addLayout(self.verticalLayout_32)
        self.verticalLayout_26.addLayout(self.horizontalLayout_15)
        self.verticalLayout_25.addLayout(self.verticalLayout_26)
        self.verticalLayoutSerial.addWidget(self.groupBoxSerialSet)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutSerial.addItem(spacerItem4)
        self.line_6 = QtWidgets.QFrame(self.frameConfigWin)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayoutSerial.addWidget(self.line_6)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutSerial.addItem(spacerItem5)
        self.groupBoxRcvSet = QtWidgets.QGroupBox(self.frameConfigWin)
        font = QtGui.QFont()
        font.setItalic(False)
        self.groupBoxRcvSet.setFont(font)
        self.groupBoxRcvSet.setFlat(False)
        self.groupBoxRcvSet.setObjectName("groupBoxRcvSet")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.groupBoxRcvSet)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.radioButtonRxAscii = QtWidgets.QRadioButton(self.groupBoxRcvSet)
        self.radioButtonRxAscii.setChecked(True)
        self.radioButtonRxAscii.setObjectName("radioButtonRxAscii")
        self.horizontalLayout_18.addWidget(self.radioButtonRxAscii)
        self.checkBoxRxRecordTime = QtWidgets.QCheckBox(self.groupBoxRcvSet)
        self.checkBoxRxRecordTime.setObjectName("checkBoxRxRecordTime")
        self.horizontalLayout_18.addWidget(self.checkBoxRxRecordTime)
        self.checkBoxRxAutoCLRF = QtWidgets.QCheckBox(self.groupBoxRcvSet)
        self.checkBoxRxAutoCLRF.setObjectName("checkBoxRxAutoCLRF")
        self.horizontalLayout_18.addWidget(self.checkBoxRxAutoCLRF)
        self.verticalLayout_36.addLayout(self.horizontalLayout_18)
        self.radioButtonRxHex = QtWidgets.QRadioButton(self.groupBoxRcvSet)
        self.radioButtonRxHex.setObjectName("radioButtonRxHex")
        self.verticalLayout_36.addWidget(self.radioButtonRxHex)
        self.verticalLayoutSerial.addWidget(self.groupBoxRcvSet)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutSerial.addItem(spacerItem6)
        self.line_7 = QtWidgets.QFrame(self.frameConfigWin)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayoutSerial.addWidget(self.line_7)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutSerial.addItem(spacerItem7)
        self.groupBoxSendSet = QtWidgets.QGroupBox(self.frameConfigWin)
        self.groupBoxSendSet.setObjectName("groupBoxSendSet")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.groupBoxSendSet)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.radioButtonTxAscii = QtWidgets.QRadioButton(self.groupBoxSendSet)
        self.radioButtonTxAscii.setChecked(True)
        self.radioButtonTxAscii.setObjectName("radioButtonTxAscii")
        self.horizontalLayout_19.addWidget(self.radioButtonTxAscii)
        self.checkBoxTxAutoCRLF = QtWidgets.QCheckBox(self.groupBoxSendSet)
        self.checkBoxTxAutoCRLF.setObjectName("checkBoxTxAutoCRLF")
        self.horizontalLayout_19.addWidget(self.checkBoxTxAutoCRLF)
        self.verticalLayout_38.addLayout(self.horizontalLayout_19)
        self.radioButtonTxHex = QtWidgets.QRadioButton(self.groupBoxSendSet)
        self.radioButtonTxHex.setObjectName("radioButtonTxHex")
        self.verticalLayout_38.addWidget(self.radioButtonTxHex)
        self.line_8 = QtWidgets.QFrame(self.groupBoxSendSet)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_38.addWidget(self.line_8)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.checkBoxTxPeriodEnable = QtWidgets.QCheckBox(self.groupBoxSendSet)
        self.checkBoxTxPeriodEnable.setObjectName("checkBoxTxPeriodEnable")
        self.horizontalLayout_20.addWidget(self.checkBoxTxPeriodEnable)
        self.lineEditPeriodMs = QtWidgets.QLineEdit(self.groupBoxSendSet)
        self.lineEditPeriodMs.setObjectName("lineEditPeriodMs")
        self.horizontalLayout_20.addWidget(self.lineEditPeriodMs)
        self.label_4 = QtWidgets.QLabel(self.groupBoxSendSet)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_20.addWidget(self.label_4)
        self.verticalLayout_38.addLayout(self.horizontalLayout_20)
        self.verticalLayout_37.addLayout(self.verticalLayout_38)
        self.verticalLayoutSerial.addWidget(self.groupBoxSendSet)
        self.verticalLayout_24.addLayout(self.verticalLayoutSerial)
        self.horizontalLayout_12.addWidget(self.frameConfigWin)
        self.horizontalLayout_12.setStretch(0, 1)
        self.verticalLayout_39.addLayout(self.horizontalLayout_12)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.verticalLayout_40.addWidget(self.dockWidget)
        SerialAssistantLXL.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SerialAssistantLXL)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 867, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        SerialAssistantLXL.setMenuBar(self.menubar)
        self.fileToolBar = QtWidgets.QToolBar(SerialAssistantLXL)
        self.fileToolBar.setObjectName("fileToolBar")
        SerialAssistantLXL.addToolBar(QtCore.Qt.TopToolBarArea, self.fileToolBar)
        self.statusBar = QtWidgets.QStatusBar(SerialAssistantLXL)
        self.statusBar.setObjectName("statusBar")
        SerialAssistantLXL.setStatusBar(self.statusBar)
        self.editToolBar = QtWidgets.QToolBar(SerialAssistantLXL)
        self.editToolBar.setObjectName("editToolBar")
        SerialAssistantLXL.addToolBar(QtCore.Qt.TopToolBarArea, self.editToolBar)
        self.toolToolBar = QtWidgets.QToolBar(SerialAssistantLXL)
        self.toolToolBar.setObjectName("toolToolBar")
        SerialAssistantLXL.addToolBar(QtCore.Qt.TopToolBarArea, self.toolToolBar)
        self.viewToolBar = QtWidgets.QToolBar(SerialAssistantLXL)
        self.viewToolBar.setObjectName("viewToolBar")
        SerialAssistantLXL.addToolBar(QtCore.Qt.TopToolBarArea, self.viewToolBar)
        self.actionSaveAsCSV = QtWidgets.QAction(SerialAssistantLXL)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/png/images/png/csvFile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAsCSV.setIcon(icon1)
        self.actionSaveAsCSV.setObjectName("actionSaveAsCSV")
        self.actionSaveAsTXT = QtWidgets.QAction(SerialAssistantLXL)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/png/images/png/txt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAsTXT.setIcon(icon2)
        self.actionSaveAsTXT.setObjectName("actionSaveAsTXT")
        self.actionSaveAsBIN = QtWidgets.QAction(SerialAssistantLXL)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/png/images/png/binary.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAsBIN.setIcon(icon3)
        self.actionSaveAsBIN.setObjectName("actionSaveAsBIN")
        self.actionSaveConfig = QtWidgets.QAction(SerialAssistantLXL)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/png/images/png/configuration.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveConfig.setIcon(icon4)
        self.actionSaveConfig.setObjectName("actionSaveConfig")
        self.actionLoadConfig = QtWidgets.QAction(SerialAssistantLXL)
        self.actionLoadConfig.setIcon(icon4)
        self.actionLoadConfig.setObjectName("actionLoadConfig")
        self.actionCRC = QtWidgets.QAction(SerialAssistantLXL)
        self.actionCRC.setCheckable(True)
        self.actionCRC.setObjectName("actionCRC")
        self.actionASCII = QtWidgets.QAction(SerialAssistantLXL)
        self.actionASCII.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/png/images/png/ascii.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionASCII.setIcon(icon5)
        self.actionASCII.setObjectName("actionASCII")
        self.actionClearSendHistory = QtWidgets.QAction(SerialAssistantLXL)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/png/images/png/editclear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClearSendHistory.setIcon(icon6)
        self.actionClearSendHistory.setObjectName("actionClearSendHistory")
        self.actionCheckSum = QtWidgets.QAction(SerialAssistantLXL)
        self.actionCheckSum.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/png/images/png/sum.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCheckSum.setIcon(icon7)
        self.actionCheckSum.setObjectName("actionCheckSum")
        self.actionHelp = QtWidgets.QAction(SerialAssistantLXL)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/png/images/png/Help_and_Support.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon8)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(SerialAssistantLXL)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/png/images/png/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon9)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAlwaysOnTop = QtWidgets.QAction(SerialAssistantLXL)
        self.actionAlwaysOnTop.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/png/images/png/top.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAlwaysOnTop.setIcon(icon10)
        self.actionAlwaysOnTop.setObjectName("actionAlwaysOnTop")
        self.actionClearReceive = QtWidgets.QAction(SerialAssistantLXL)
        self.actionClearReceive.setIcon(icon6)
        self.actionClearReceive.setObjectName("actionClearReceive")
        self.actionClearSend = QtWidgets.QAction(SerialAssistantLXL)
        self.actionClearSend.setIcon(icon6)
        self.actionClearSend.setObjectName("actionClearSend")
        self.actionClearAll = QtWidgets.QAction(SerialAssistantLXL)
        self.actionClearAll.setIcon(icon6)
        self.actionClearAll.setObjectName("actionClearAll")
        self.actionLayoutHorizontal = QtWidgets.QAction(SerialAssistantLXL)
        self.actionLayoutHorizontal.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/png/images/png/Horizontal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLayoutHorizontal.setIcon(icon11)
        self.actionLayoutHorizontal.setObjectName("actionLayoutHorizontal")
        self.actionLayoutVertical = QtWidgets.QAction(SerialAssistantLXL)
        self.actionLayoutVertical.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/png/images/png/Vertical.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLayoutVertical.setIcon(icon12)
        self.actionLayoutVertical.setObjectName("actionLayoutVertical")
        self.actionLayoutGrid = QtWidgets.QAction(SerialAssistantLXL)
        self.actionLayoutGrid.setCheckable(True)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/png/images/png/grid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLayoutGrid.setIcon(icon13)
        self.actionLayoutGrid.setObjectName("actionLayoutGrid")
        self.actionLayoutUserDefine = QtWidgets.QAction(SerialAssistantLXL)
        self.actionLayoutUserDefine.setCheckable(True)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/png/images/png/layoutUserDefine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLayoutUserDefine.setIcon(icon14)
        self.actionLayoutUserDefine.setObjectName("actionLayoutUserDefine")
        self.actionOpen = QtWidgets.QAction(SerialAssistantLXL)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/png/images/png/fileopen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon15)
        self.actionOpen.setObjectName("actionOpen")
        self.actionFind = QtWidgets.QAction(SerialAssistantLXL)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/png/images/png/increase.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFind.setIcon(icon16)
        self.actionFind.setObjectName("actionFind")
        self.actionConfig = QtWidgets.QAction(SerialAssistantLXL)
        self.actionConfig.setCheckable(True)
        self.actionConfig.setChecked(True)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/png/images/png/configuration1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfig.setIcon(icon17)
        self.actionConfig.setObjectName("actionConfig")
        self.actionStatisticalPie = QtWidgets.QAction(SerialAssistantLXL)
        self.actionStatisticalPie.setCheckable(True)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/png/images/png/stats_pie.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStatisticalPie.setIcon(icon18)
        self.actionStatisticalPie.setObjectName("actionStatisticalPie")
        self.actionOption = QtWidgets.QAction(SerialAssistantLXL)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/png/images/png/slider_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOption.setIcon(icon19)
        self.actionOption.setObjectName("actionOption")
        self.actionStatisticalHist = QtWidgets.QAction(SerialAssistantLXL)
        self.actionStatisticalHist.setCheckable(True)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/png/images/png/stats_hist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStatisticalHist.setIcon(icon20)
        self.actionStatisticalHist.setObjectName("actionStatisticalHist")
        self.actionStatisticalLine = QtWidgets.QAction(SerialAssistantLXL)
        self.actionStatisticalLine.setCheckable(True)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/png/images/png/stats_lines.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStatisticalLine.setIcon(icon21)
        self.actionStatisticalLine.setObjectName("actionStatisticalLine")
        self.actionPrint = QtWidgets.QAction(SerialAssistantLXL)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/png/images/png/print1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon22)
        self.actionPrint.setObjectName("actionPrint")
        self.actionPrintPreview = QtWidgets.QAction(SerialAssistantLXL)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/png/images/png/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrintPreview.setIcon(icon23)
        self.actionPrintPreview.setObjectName("actionPrintPreview")
        self.actionClose = QtWidgets.QAction(SerialAssistantLXL)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/png/images/png/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon24)
        self.actionClose.setObjectName("actionClose")
        self.actionQuit = QtWidgets.QAction(SerialAssistantLXL)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/png/images/png/filequit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon25)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCalculator = QtWidgets.QAction(SerialAssistantLXL)
        self.actionCalculator.setCheckable(True)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/png/images/png/calculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCalculator.setIcon(icon26)
        self.actionCalculator.setObjectName("actionCalculator")
        self.actionCalendar = QtWidgets.QAction(SerialAssistantLXL)
        self.actionCalendar.setCheckable(True)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/png/images/png/calendar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCalendar.setIcon(icon27)
        self.actionCalendar.setObjectName("actionCalendar")
        self.actionToolBarDisplay = QtWidgets.QAction(SerialAssistantLXL)
        self.actionToolBarDisplay.setCheckable(True)
        self.actionToolBarDisplay.setChecked(True)
        self.actionToolBarDisplay.setObjectName("actionToolBarDisplay")
        self.actionEditBarDisplay = QtWidgets.QAction(SerialAssistantLXL)
        self.actionEditBarDisplay.setCheckable(True)
        self.actionEditBarDisplay.setChecked(True)
        self.actionEditBarDisplay.setObjectName("actionEditBarDisplay")
        self.actionFileBarDispaly = QtWidgets.QAction(SerialAssistantLXL)
        self.actionFileBarDispaly.setCheckable(True)
        self.actionFileBarDispaly.setChecked(True)
        self.actionFileBarDispaly.setObjectName("actionFileBarDispaly")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSaveAsTXT)
        self.menuFile.addAction(self.actionSaveAsBIN)
        self.menuFile.addAction(self.actionSaveAsCSV)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoadConfig)
        self.menuFile.addAction(self.actionSaveConfig)
        self.menuFile.addAction(self.actionOption)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrintPreview)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionQuit)
        self.menuTools.addAction(self.actionASCII)
        self.menuTools.addAction(self.actionCRC)
        self.menuTools.addAction(self.actionCheckSum)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionStatisticalPie)
        self.menuTools.addAction(self.actionStatisticalHist)
        self.menuTools.addAction(self.actionStatisticalLine)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionCalculator)
        self.menuTools.addAction(self.actionCalendar)
        self.menuView.addAction(self.actionAlwaysOnTop)
        self.menuView.addAction(self.actionFileBarDispaly)
        self.menuView.addAction(self.actionEditBarDisplay)
        self.menuView.addAction(self.actionToolBarDisplay)
        self.menuView.addAction(self.actionConfig)
        self.menuView.addSeparator()
        self.menuEdit.addAction(self.actionFind)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionClearSend)
        self.menuEdit.addAction(self.actionClearSendHistory)
        self.menuEdit.addAction(self.actionClearReceive)
        self.menuEdit.addAction(self.actionClearAll)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.fileToolBar.addAction(self.actionOpen)
        self.fileToolBar.addSeparator()
        self.fileToolBar.addAction(self.actionSaveAsTXT)
        self.fileToolBar.addAction(self.actionSaveAsBIN)
        self.fileToolBar.addAction(self.actionSaveAsCSV)
        self.fileToolBar.addSeparator()
        self.fileToolBar.addAction(self.actionLoadConfig)
        self.fileToolBar.addAction(self.actionSaveConfig)
        self.fileToolBar.addAction(self.actionOption)
        self.fileToolBar.addSeparator()
        self.fileToolBar.addAction(self.actionPrintPreview)
        self.fileToolBar.addAction(self.actionPrint)
        self.editToolBar.addAction(self.actionFind)
        self.editToolBar.addSeparator()
        self.editToolBar.addAction(self.actionClearReceive)
        self.editToolBar.addAction(self.actionClearAll)
        self.editToolBar.addAction(self.actionClearSendHistory)
        self.editToolBar.addAction(self.actionClearSend)
        self.toolToolBar.addAction(self.actionASCII)
        self.toolToolBar.addAction(self.actionCRC)
        self.toolToolBar.addAction(self.actionCheckSum)
        self.toolToolBar.addSeparator()
        self.toolToolBar.addAction(self.actionStatisticalPie)
        self.toolToolBar.addAction(self.actionStatisticalHist)
        self.toolToolBar.addAction(self.actionStatisticalLine)
        self.toolToolBar.addSeparator()
        self.toolToolBar.addAction(self.actionCalculator)
        self.toolToolBar.addAction(self.actionCalendar)
        self.viewToolBar.addAction(self.actionAlwaysOnTop)
        self.viewToolBar.addAction(self.actionConfig)
        self.viewToolBar.addSeparator()
        self.viewToolBar.addAction(self.actionLayoutHorizontal)
        self.viewToolBar.addAction(self.actionLayoutVertical)
        self.viewToolBar.addAction(self.actionLayoutGrid)
        self.viewToolBar.addAction(self.actionLayoutUserDefine)
        self.viewToolBar.addSeparator()
        self.label_3.setBuddy(self.comboBoxBand)
        self.label_4.setBuddy(self.lineEditPeriodMs)

        self.retranslateUi(SerialAssistantLXL)
        self.comboBoxBand.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(SerialAssistantLXL)

    def retranslateUi(self, SerialAssistantLXL):
        _translate = QtCore.QCoreApplication.translate
        SerialAssistantLXL.setWindowTitle(_translate("SerialAssistantLXL", "SerialAssistantLXL"))
        self.textEditSend.setWhatsThis(_translate("SerialAssistantLXL", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButtonSend.setText(_translate("SerialAssistantLXL", "Send"))
        self.pushButtonClear.setText(_translate("SerialAssistantLXL", "Clear All"))
        self.groupBoxSerialSet.setTitle(_translate("SerialAssistantLXL", "Serial Set"))
        self.comboBoxPort.setItemText(0, _translate("SerialAssistantLXL", "No Port Can Be Use"))
        self.pushButtonOpen.setText(_translate("SerialAssistantLXL", "Open"))
        self.label_3.setText(_translate("SerialAssistantLXL", "BandRate"))
        self.groupBox_datasize.setTitle(_translate("SerialAssistantLXL", "Datas"))
        self.radioButtonData8Bit.setText(_translate("SerialAssistantLXL", "8Bit"))
        self.radioButtonData7Bit.setText(_translate("SerialAssistantLXL", "7Bit"))
        self.radioButtonData6Bit.setText(_translate("SerialAssistantLXL", "6Bit"))
        self.radioButtonData5Bit.setText(_translate("SerialAssistantLXL", "5Bit"))
        self.groupBoxParity.setTitle(_translate("SerialAssistantLXL", "Checks"))
        self.radioButtonParityNone.setText(_translate("SerialAssistantLXL", "None"))
        self.radioButtonParityEven.setText(_translate("SerialAssistantLXL", "Even"))
        self.radioButtonParityOdd.setText(_translate("SerialAssistantLXL", "Odd"))
        self.radioButtonParityMark.setText(_translate("SerialAssistantLXL", "Mark"))
        self.radioButtonSpace.setText(_translate("SerialAssistantLXL", "Space"))
        self.groupBoxHardFlowCtl.setTitle(_translate("SerialAssistantLXL", "HardFlowCtl"))
        self.checkBoxFlowCtrl.setText(_translate("SerialAssistantLXL", "RTS/CTS"))
        self.groupBoxStops.setTitle(_translate("SerialAssistantLXL", "Stops"))
        self.radioButtonStop1Bit.setText(_translate("SerialAssistantLXL", "1Bit"))
        self.radioButtonStop1_5Bit.setText(_translate("SerialAssistantLXL", "1.5Bit"))
        self.radioButtonStop2Bit.setText(_translate("SerialAssistantLXL", "2Bit"))
        self.groupBoxRcvSet.setTitle(_translate("SerialAssistantLXL", "Receive Set"))
        self.radioButtonRxAscii.setText(_translate("SerialAssistantLXL", "ASCII"))
        self.checkBoxRxRecordTime.setText(_translate("SerialAssistantLXL", "Log Time"))
        self.checkBoxRxAutoCLRF.setText(_translate("SerialAssistantLXL", "Auto Wrap"))
        self.radioButtonRxHex.setText(_translate("SerialAssistantLXL", "Hex"))
        self.groupBoxSendSet.setTitle(_translate("SerialAssistantLXL", "Send Set"))
        self.radioButtonTxAscii.setText(_translate("SerialAssistantLXL", "ASCII"))
        self.checkBoxTxAutoCRLF.setText(_translate("SerialAssistantLXL", "Suffix CR/LF"))
        self.radioButtonTxHex.setText(_translate("SerialAssistantLXL", "Hex"))
        self.checkBoxTxPeriodEnable.setWhatsThis(_translate("SerialAssistantLXL", "<html><head/><body><p><br/></p></body></html>"))
        self.checkBoxTxPeriodEnable.setText(_translate("SerialAssistantLXL", "Period Send"))
        self.lineEditPeriodMs.setText(_translate("SerialAssistantLXL", "1000"))
        self.label_4.setText(_translate("SerialAssistantLXL", "ms"))
        self.menuFile.setTitle(_translate("SerialAssistantLXL", "File"))
        self.menuTools.setTitle(_translate("SerialAssistantLXL", "Tool"))
        self.menuView.setTitle(_translate("SerialAssistantLXL", "View"))
        self.menuEdit.setTitle(_translate("SerialAssistantLXL", "Edit"))
        self.menuHelp.setTitle(_translate("SerialAssistantLXL", "Help"))
        self.fileToolBar.setWindowTitle(_translate("SerialAssistantLXL", "toolBar"))
        self.editToolBar.setWindowTitle(_translate("SerialAssistantLXL", "toolBar"))
        self.toolToolBar.setWindowTitle(_translate("SerialAssistantLXL", "toolBar"))
        self.viewToolBar.setWindowTitle(_translate("SerialAssistantLXL", "toolBar"))
        self.actionSaveAsCSV.setText(_translate("SerialAssistantLXL", "Save As CSV"))
        self.actionSaveAsTXT.setText(_translate("SerialAssistantLXL", "Save As TXT"))
        self.actionSaveAsTXT.setShortcut(_translate("SerialAssistantLXL", "Ctrl+S"))
        self.actionSaveAsBIN.setText(_translate("SerialAssistantLXL", "Save As BIN"))
        self.actionSaveConfig.setText(_translate("SerialAssistantLXL", "Save Config"))
        self.actionLoadConfig.setText(_translate("SerialAssistantLXL", "Load Config"))
        self.actionCRC.setText(_translate("SerialAssistantLXL", "CRC"))
        self.actionASCII.setText(_translate("SerialAssistantLXL", "ASCII"))
        self.actionClearSendHistory.setText(_translate("SerialAssistantLXL", "ClearSendHistory"))
        self.actionClearSendHistory.setToolTip(_translate("SerialAssistantLXL", "ClearSendHistory"))
        self.actionCheckSum.setText(_translate("SerialAssistantLXL", "CheckSum"))
        self.actionHelp.setText(_translate("SerialAssistantLXL", "Help"))
        self.actionAbout.setText(_translate("SerialAssistantLXL", "About"))
        self.actionAlwaysOnTop.setText(_translate("SerialAssistantLXL", "AlwaysOnTop"))
        self.actionClearReceive.setText(_translate("SerialAssistantLXL", "ClearReceive"))
        self.actionClearReceive.setToolTip(_translate("SerialAssistantLXL", "ClearReceive"))
        self.actionClearSend.setText(_translate("SerialAssistantLXL", "ClearSend"))
        self.actionClearSend.setToolTip(_translate("SerialAssistantLXL", "ClearSend"))
        self.actionClearAll.setText(_translate("SerialAssistantLXL", "ClearAll"))
        self.actionClearAll.setToolTip(_translate("SerialAssistantLXL", "ClearAll"))
        self.actionLayoutHorizontal.setText(_translate("SerialAssistantLXL", "LayoutHorizontal"))
        self.actionLayoutVertical.setText(_translate("SerialAssistantLXL", "LayoutVertical"))
        self.actionLayoutGrid.setText(_translate("SerialAssistantLXL", "LayoutGrid"))
        self.actionLayoutUserDefine.setText(_translate("SerialAssistantLXL", "LayoutUserDefine"))
        self.actionOpen.setText(_translate("SerialAssistantLXL", "Open"))
        self.actionOpen.setShortcut(_translate("SerialAssistantLXL", "Ctrl+O"))
        self.actionFind.setText(_translate("SerialAssistantLXL", "Find"))
        self.actionFind.setShortcut(_translate("SerialAssistantLXL", "Ctrl+F"))
        self.actionConfig.setText(_translate("SerialAssistantLXL", "ConfigWin"))
        self.actionStatisticalPie.setText(_translate("SerialAssistantLXL", "StatisticalPie"))
        self.actionOption.setText(_translate("SerialAssistantLXL", "Option"))
        self.actionStatisticalHist.setText(_translate("SerialAssistantLXL", "StatisticalHist"))
        self.actionStatisticalLine.setText(_translate("SerialAssistantLXL", "StatisticalLine"))
        self.actionPrint.setText(_translate("SerialAssistantLXL", "Print"))
        self.actionPrintPreview.setText(_translate("SerialAssistantLXL", "PrintPreview"))
        self.actionClose.setText(_translate("SerialAssistantLXL", "Close"))
        self.actionQuit.setText(_translate("SerialAssistantLXL", "Quit"))
        self.actionCalculator.setText(_translate("SerialAssistantLXL", "Calculator"))
        self.actionCalendar.setText(_translate("SerialAssistantLXL", "Calendar"))
        self.actionToolBarDisplay.setText(_translate("SerialAssistantLXL", "ToolBar"))
        self.actionToolBarDisplay.setToolTip(_translate("SerialAssistantLXL", "ToolBarDisplay"))
        self.actionEditBarDisplay.setText(_translate("SerialAssistantLXL", "EditBar"))
        self.actionEditBarDisplay.setToolTip(_translate("SerialAssistantLXL", "EditBarDisplay"))
        self.actionFileBarDispaly.setText(_translate("SerialAssistantLXL", "FileBar"))

import GUI_Source_rc
